### ISSUE TITLE
Using a HOC and passing it different components to gain access to Redux store

### ISSUE THREAD

**Issue by 4xDMG** [reactbris/meetup#40]
One of my coworkers was disappointed when he found out that Redux didn't completely eliminate the need to pass state down as props to child components. Instead of using the container component pattern he decided to create a HOC that is connected to the store and then pass in different components to give them access to it.

For example he has a route('/1') and off that main route, 3 subroutes ('/1/a','/1/b','/1/b'). Whenever there's a route change he passes the "component" for that route to the HOC so it has access to the store.

Is this an anti-pattern? Isn't it better to have a connected container that you use to render the subroutes and just pass the necessary props to those components?

**Comment by iamtommcc** [comment]
Definitely seems a little strange – without seeing a code sample, hard to evaluate whether or not it's an anti-pattern *per se*. How are these components being passed along to the HoC, exactly? If all these components are just being fed *the whole store*, then that's definitely a bad smell: it pays to be explicit with what data the component depends on.

But regardless, your right: idiomatic React/Redux should involve selectively passing props down as required. Redux can help avoid awkward situations where you need to pass props down through many layers, but passing things down 1 or 2 layers with Redux is still common.
