### ISSUE TITLE
Job Posting: Mid-level developer. React-Native, typescript, firebase, serverless GCF backend

### ISSUE THREAD

**Issue by chris-divvito** [reactbris/meetup#48]
# Divvito – Mid Developer

Divvito helps separated parents communicate more effectively. We have developed a messaging app, Divvito Messenger, that mitigates inappropriate communication between parents. We’ve seen a 50% reduction in flagged messages with the first four weeks of use.

This role is a unique opportunity for the right candidate. While based in Brisbane, we will be pushing heavily into global markets mid 2019.

## RESPONSIBILITIES

- Write great code, code that is legible, pithy, efficient, modular, well-tested and handles any edge case you throw
at it
- Design and implement front-end interfaces, underlying APIs, and serverless backend systems
- Collect and process data from multiple platforms and APIs
- Play a critical role in all architecture, code, testing and deployment decisions
- Design and implement native applications
- Troubleshoot and support system and application problems
- Ask questions to understand requirements
- Dive in and solve problems, big and small

## QUALIFICATIONS
- Don’t care ...
- Minimum 5 years of development experience
- Self-motivated, passionate attitude with the desire to take ownership and keep moving

## REQUIRED SKILLS
- Excellent communication (both written and verbal) and teamwork skills
- Proficiency with Javascript/Typescript, React and/or React Native.
- Working knowledge of cloud services like (bonus if familiar with Google Cloud services such as Firestore, GCM, etc)
- Strong working knowledge of JSON and API usage
- Work creatively to solve challenging problems
- Strong focus on delivering quality code. TDD, test automation skills etc

## BONUS POINTS
- Experience with native app development (eg Objective-C for IOS, Java for Android)
- Have worked with Natural Language Programming in the past
- Experience with machine learning systems
- Experience with distributed source control systems (preferably Git)

If you have an insatiable appetite to learn, are a good communicator, great listener, work well in a team and also autonomously, this role would be perfect for you.

**_Commence late July._**

Send through an email introduction, including your CV to chris@divvito.com.

**Comment by loklaan** [comment]
Hi @chris-divvito!

Hope the postings are doing well. Would you like to keep this one up for another month?

**Comment by chris-divvito** [comment]
Hey, sorry for the slow response, We've filled the position, thanks very much
