### ISSUE TITLE
Requested topic: Squashing Redux concerns into GraphQL Clients

### ISSUE THREAD

**Issue by loklaan** [reactbris/meetup#51]
If you've never seen popular GQL clients in action, as a frontender, this introduction can be really eye opening.

The redux data layer of your frontend app can _easily_ balloon into a monstrosity of verbose action/reducers, and while the management of all-that is a topic within itself, jumping off of the wagon onto a similar solution like Apollo (a popular GQL client) can reduce to amount of research and work you would otherwise have infront of you... Allowing you to focus on UI & polish!

This request is fairly specific, but it's trending hard in React community at the moment so there might be a few that'd want to pick it up!  
Alternatively I'd be interested to hear about another other kind of talks that center around data layer management for React apps.

**Comment by Maxim-Filimonov** [comment]
I can give a talk on that topic. During my time mentoring at coding boot camp I did find that Redux is a very complex solution and gets beginners confused a lot. 
With GraphQL it's way simpler... until you need to update your client cache :-D

**Comment by loklaan** [comment]
@Maxim-Filimonov Hey mate!

Thank sounds amazing. We'd love you feature you in the upcoming meetup!

I think this topic is really important, and a lot of folks have expressed keen interest in hearing about it (from any kind of angle).

Let's get this going; steps from here are to
1. expand on the above, in either going down the GQL route of client-side state management, or something else like Mobx.
  _Creating a new github issue will help with the above._
2. Land on a date. Would you be good to speak at this coming Monday's meetup? We're short on spots, as per usual, but this talk would take priority regardless.

**Comment by Maxim-Filimonov** [comment]
In reverse order :trollface: 
2. I can prepare the talk over the weekend, no worries. Improv is the best, anyway ;)

1. Depends on the preferred focus area for the talk: 
- **State management conceptually** - I can talk about state management as a concept and give examples of MobX / Redux/others as possible solutions for specific problems. Redux has a specific use case it was designed for, the concern with it is that we often forget what was the use case and used as the silver bullet.
- **Side by side examples of using GraphQL vs Rest API** - show simple examples of using the same API with GraphQL vs using it with Redux.

I think the second one would be easier as more abstract one will take more time to prepare.

**Comment by loklaan** [comment]
I think you're right. It's easy to relate to CRUD glue, so the side-by-side should roll over perfectly.

Brilliant!

I usually write titles & small intro's for the talks. They go up on the meetup page and twitter. I'm time-poor this weekend and will be rushing as is - would you like to help out an extra tad and come up with these for you talk? Have a look at past meetup pages for inspo.

Thanks again! Hit me up here, or at lochlan@reactbris.org, if you need to chat

**Comment by Maxim-Filimonov** [comment]
how about some FP humour ? - "Reducing Redux with GraphQL"

**Comment by loklaan** [comment]
Ha, that's great, good one. I'll extrapolate a description.

**Comment by Maxim-Filimonov** [comment]
Wonder does many people want to hear about the fundamental difference between GraphQL and REST? Thinking of it as good intro

**Comment by loklaan** [comment]
Probably, but that's a different topic hahaha

**Comment by Maxim-Filimonov** [comment]
I know right :) So I will cut the introduction to the minimum, presuming that most people are aware of the difference.
