### ISSUE TITLE
Contributing to Open-Source Projects

### ISSUE THREAD

**Issue by cartant** [reactbris/meetup#52]
Hi. I've recently accepted a position at Rexlabs and Harold - the recruiter who matched me with the company - has mentioned that ReactBris is seeking another talk for the Monday, 24 September meetup.

I don't have any React-specific talks prepared, at the moment, but I have been compiling notes for a talk on why developers should - and how they can - contribute to open-source projects.

I've been a maintainer and contributor for the last two years and I'm currently a member of the RxJS core team. It would be a 20 minute talk and would cover the following:

* Why you might want to consider contributing.
* The different ways in which you can contribute.
* What maintainers really appreciate.
* Some things about which maintainers are cautious.
* Some things to avoid - i.e. maintainers' pet peeves.
* How to start contributing.

If you'd like me to present it, I'd be delighted to do so.

**Comment by loklaan** [comment]
Nicholas this sounds *great*! I'm delighted that you're delighted haha ✨ 

I think the topic will be well received.

I'll lock it in, and be in contact with you (via twitter) later in the week with any extra details you may need.

**Comment by patrickgordon** [comment]
Sounds like a great talk. Only recently started contributing to open source projects (that aren't my own) and definitely think this would be helpful.

**Comment by cartant** [comment]
If anyone is interested, the slides from the presentation are [here](http://cdn.s3.cartant.com/reactbris-2018-09-24/index.html).

There is more information on contributing to open-source software here:

* [How to Contribute to Open Source](https://opensource.guide/how-to-contribute/)
* [Guide to Idiomatic Contributing](https://github.com/jonschlinkert/idiomatic-contributing)

There are some examples of what not to do here:

* [Dear GitHub](https://github.com/dear-github/dear-github/blob/master/README.md)

And the PR that was delayed by the Ukranian revolution is [here](https://github.com/fre5h/DoctrineEnumBundle/pull/12).

Also, I can heartily recommend [`mdx-deck`](https://github.com/jxnblk/mdx-deck) for authoring slides.

**Comment by loklaan** [comment]
Thanks again Nicholas!
