### ISSUE TITLE
TechnologyOne and ReactJs

### ISSUE THREAD

**Issue by Jesseppi** [reactbris/meetup#53]
A talk about **TechnologyOne's** recent adoption of the **ReactJS** framework. 
Detailing:
-  the journey to adopting React as part of TechnologyOne's stack
-  how the development of a **custom Design System** came about and the benefits it provides
-  the evolution of an **Internal component library**
-  **Deployment** on an enterprise scale.

This presentation will include high levels sarcasm, a smattering of sass and some charm.

**Comment by loklaan** [comment]
Thanks for submitting Jesse! I'm stoked!

**Comment by loklaan** [comment]
Thanks again Jesse!

Feel free to reply with resources of the talk, like a link to the slides etc. Not required, but appreciated.
