### ISSUE TITLE
React in an enterprise cloud environment

### ISSUE THREAD

**Issue by scotartt** [reactbris/meetup#54]
I can offer a talk around the use of React in an "enterprise" cloud environment. We (as in, Virgin Australia, the company I work for) are migrating our very out-of-date data centre based "enterprise" environment to a brand new environment running the services layer in Kubernetes hosted in AWS. My focus in the this effort has been in three main areas: the automated build pipeline (on Gitlab CI); the micro-services environment for the airline operations systems; and introducing React as a platform for delivering customised web applications and information systems to our workforce; all in an agile (kanban) methodology and standing up a brand-new Devops team to design, build, and run these new applications and services.

I guess some of this will be much more about how React fits together will all these other pieces in the highly dynamic, yet very logistically disciplined environment which is airline operations; what sort of challenges we face; how to talk to management about these issues and gain approval to deliver new apps with React.

**Comment by loklaan** [comment]
Sounds good Scot, although perhaps too broad.

Would you be able to tighten the scope of the talk to avoid spooling into the challenges of DevOps (despite it being a great topic on its own)?

P.S. You might like to present & talk on the services layer changes you and the team are making at the API and Microservices Meetup. It's on this month, and reoccurs every two months.

**Comment by scotartt** [comment]
Hi Loklaan

Yes, I will have a think about how I can best tighten the scope to ensure it will focus around React over the next few days. 

My initial thoughts fall to something like "The challenges of using React to deliver custom apps for airline operations". This might present some interesting points of difference from public-facing applications, especially in the capabilities of delivering a React app into the end-user computing environment of workers around an airport terminal and aircraft ramp.

**Comment by loklaan** [comment]
Hi Scot!

This talk has grit! I like the tightened direction a lot. I think there will be more than a few enterprise frontend folks that'd be keen on it.

Also I've always been interested to know what runs the in-house airline gadgets!!

Let me know if you want to move ahead on this; there are spots available on this upcoming Monday's meetup.

**Comment by scotartt** [comment]
Well, yep, I can put together the presentation this weekend. What's the optimum length?
