### ISSUE TITLE
Intro to Reason React

### ISSUE THREAD

**Issue by anisjonischkeit** [reactbris/meetup#56]
I'm using Reason React in a side project and am so far liking it.

The talk could cover:
 - What ReasonML does well (why people are excited about it)
 - What warts I have come across so far
 - How to get started with Reason React

**Comment by jwulf** [comment]
Reason is the future.

**Comment by loklaan** [comment]
@anisjonischkeit Sounds amazing!

I've personally been keen to hear a talk on this, even more-so after seeing your agenda.

When would you be keen to present? Next year when we're back? At tonights Meetup we're opening the floor to lightning talks so you could do a condensed version if you're able to make it...

Looking forward to hearing back from ya

**Comment by loklaan** [comment]
@anisjonischkeit Hey mate, would you like to present in Feb 😃

**Comment by anisjonischkeit** [comment]
Yep sounds good.

**Comment by anisjonischkeit** [comment]
Heart of the Valley is way easier for me :). 

Some guidance would definitely be appreciated. I'll probably send you a message closer to February. Is twitter a good place to contact you?

**Comment by loklaan** [comment]
Yup that's a good place.
