### ISSUE TITLE
Senior Full Stack Developer (React.js & Node.js also Ruby, Rails)

### ISSUE THREAD

**Issue by mikerubio720** [reactbris/meetup#57]
Hey guys & girls!
I’m working with an established tech startup Outfit.io who’s coming off the back of a sales cycle and after having won a stack of new business they are ready to grow their team for the future. The opportunity to work with world-class technologies and develop solutions that will be adopted on a global scale. We want to hire exceptional talent to grow the Outfit platform and brand. This is a tech central company that from the leadership down, so they value their quality product and best practice development processes in a creative, collaborative environment. At Outfit, there is genuine, ongoing opportunities to develop your career towards team or technical leadership. This position reports to the Head of Technology.

**The Scope**
This role revolves around their unique design, marketing software product. You’ll be delivering production-ready solutions, working across the full tech stack. While working as a key member of the dev team you’ll be contributing to all phases of the development life cycle; troubleshooting and testing; production of systems design artefacts such as integration plans, wire-frames, process or workflow designs, and functional design documents. 
As a senior dev you’ll be expected to contribute in mentoring younger dev’s with scope to move into a team lead position down the track. 

**Successful Applicants**
While a passion for elegant code and development best practices are a must we’re also looking for someone with great soft skills. This means that you can comfortably talk tech with non-techies and it makes sense. You’re equally at home with headphones on, head in your monitors and meeting with business leaders assessing technical requirements and helping solve problems and explain solutions. 
A couple of key aspects that you need to have experience in:
-	Strong commercial Front and Backend Experience (ideally 8+ years)
-	Ruby, Rails
-	JavaScript
-	Golang
-	React.js
-	Node.js
-	Strong commercial experience in API Design
-	RESTful, SOAP and GraphQL interfaces
-	Excellent creative problem solving

**Get In Touch**
We start relationships and conversations without preconceived ideas of where the road should take you. Let's get to know each other. Reach out to Mike on 0433 011 409 I’d love to chat.

**Comment by loklaan** [comment]
@mikerubio720 Hey mate, are you able to add transparent details about the role?
eg. the company, their values, their history etc

I don't want to be hostile towards recruitment, but I need to extra information for it to be helpful for our meetup members.

**Comment by mikerubio720** [comment]
No worries I'm just checking this with my client, I don't think it'll be an issue but I want to make sure I have their permission to give more of their details. I'll update this soon
