### ISSUE TITLE
React for static websites with Gatsbyjs

### ISSUE THREAD

**Issue by Maxim-Filimonov** [reactbris/meetup#58]
We have been moving our public website from hosted solution to Gatsbyjs recently. 
I find it a pleasure to work with and would love to share my experience with it. 

Gatsbyjs designed to help build modern data driven websites hosted statically. So called JAM stack.

**Comment by loklaan** [comment]
Hey @Maxim-Filimonov !

What would the talk/your experiences be comprised of? I'm asking because Gatsby was talk about in Sept (or maybe earlier...) last year, and I've love this talk to flip the script.

**Comment by loklaan** [comment]
I like the sound of that! Gotcha's are soooo important to share :)

Could we queue this up for a future meetup... maybe March?

I'll need the following from ya:

* Title
* Short and long form description, which are used on Meetup and Twitter
* Length of talk (we're generous, but try ya best to stay within your estimate. :)
* Your Twitter handle, if you'd like me to tag you in posts

**Comment by iamtommcc** [comment]
Hi @Maxim-Filimonov, would you still be interested in delivering this talk? I think it'd be really interesting, and people would love to hear about someone's realistic experiences with Gatsby (good and bad 😉 ).

**Comment by Maxim-Filimonov** [comment]
That's going to be a difficult one as I have left Brisbane. No plans to come back at the moment.

**Comment by iamtommcc** [comment]
Hahaha fair enough mate! Thanks anyway :+1:
