### ISSUE TITLE
Why Suspense will be a game changer

### ISSUE THREAD

**Issue by julianburr** [reactbris/meetup#60]
I'm still hyped about React Suspense (even though it will still be a bit till it's going into stable release). Would basically like to cover:

 * basic technical explanation of what Suspense is (basically a very brief summary of my talk last year)
 * focus the rest of the talk on how it changes how we will architect our apps and think about loading states (just like error boundaries did/do for error states) giving some examples and how this aligns development more with the mental models of loading states UX/UI designers have

**Comment by loklaan** [comment]
Brilliant Julian, can't wait!

Would you mind generating description of the talk, which will make it's way into Meetup & Twitter?

**Comment by julianburr** [comment]
Will think of an outline this weekend and shoot through a description here :+1:

**Comment by julianburr** [comment]
@loklaan ok, elevator pitch doesn't change much:

Why React Suspense will be a game changer - How Suspense will transform the way we think about loading states and architect our apps

Let me know if you need more details ... quite a bit to cover, but I'll make sure to squeeze it into the 30min time frame :wink: Next meetup is 25th Feb, correct?

**Comment by loklaan** [comment]
Correct! Thanks for this description! I think it's fine, albeit succinct 🤣
