### ISSUE TITLE
Part-time Fullstack Engineer at Gilt Investments 

### ISSUE THREAD

**Issue by KathrynAWalker** [reactbris/meetup#61]
## Gilt Investments

Gilt Investments is a fixed income specialist firm, offering fixed income products to the Australian public as a secure alternative to volatile and high-risk investments such as shares and property.  We currently operate on a service based model, whereby we provide guidance on the construction of Fixed Income portfolios for our clients.  

Gilt Investments is seeking to automate some of the services offered through a range of online tools. As a software engineer at Gilts you would be part of the team delivering the initial product release along with defining the infrastructure for future features and products. 

### About the Role

The successful applicant will work as part of a US based team, and will be accountable to the Brisbane based Managing Director.  We are seeking a motivated individual with demonstrated knowledge of developing across the stack.

You should be comfortable with database setup, RESTful API design and modern frontend frameworks.  You will be able to work independently, as technical guidance and design direction will often not be received in real time due to time differences with the US team.

We are seeking commitment for 16 hours per week.  You will have the flexibility to work most of this time in hours of your choosing.

### Responsibilities

* Develop across the stack (frontend, backend API development and small amounts of server management), 
* Build and maintain infrastructure for scalability and reliability,
* Design API's

##### What we are looking for:

* Strong knowledge of Version Control (Git, Mercurial, SVN)
* Experience with Unix based systems
* Strong knowledge of Javascript
* Database fundamentals
* RESTful API knowledge

##### Bonus points for having experience in:

* Reactjs
* Postgres
* Golang (Gin framework)
* Google Cloud Platform (GCS, Compute Engine)

### How to Apply

If you think you are right for this job or would like to know more, please contact:  
support@gilts.com.au

**Comment by loklaan** [comment]
Hey @KathrynAWalker, friendly ping to check if this is still relevant?
