### ISSUE TITLE
Recruitment Q&A

### ISSUE THREAD

**Issue by theharold9000** [reactbris/meetup#63]
## Summary of talk

What tech is in demand? How do you ACTUALLY attract top developers? Which recruiters are actually good? All questions will be answered, you just have to ask them.

## Details

**Title of the Talk**  
Recruiting participants for a Q&A with a recruiter on recruitment.

**Description of the Talk**  
There's a lot of hearsay, opinion and general questions around all things recruitment. As a recruiter who spends his days speaking with developers, dev managers and CTOs, I wouldn't say I have all the answers but I'd like to think I'm a pretty reputable source.

I want this to be as much of an open dialogue as possible so having questions prepared ahead of this is encouraged! Nothing is off-limits so fire at will; popular tech, salary negotiations, whatever. You ask it, I'll do my best to answer it. 

**My Info**  
@theharold9000

**Comment by loklaan** [comment]
@theharold9000 Want to do it again this Feb event?

**Comment by theharold9000** [comment]
@loklaan Yep let's do it. I may be doing one at BrisJS already but it's unconfirmed and regardless, it never hurts to have more Q&As 😃

**Comment by jwulf** [comment]
I'm Josh Wulf, and I endorse this message.
