### ISSUE TITLE
[Full Time] Full-stack developer at DoseMe

### ISSUE THREAD

**Issue by MichaelDorkhom** [reactbris/meetup#64]
![image](https://user-images.githubusercontent.com/10858275/53383737-60af8680-39c4-11e9-8e5b-9709b9e16530.png)
DoseMe is looking at hiring a full time intermediate full-stack developer. By joining the team you will be able to apply your skills to develop software used to improve patient care in hospitals around the world!

We develop a real-time precision dosing software designed for clinicians to predict the optimal dose of medications that require therapeutic drug monitoring. DoseMeRx is currently used across five continents in hundreds of hospitals.

## About the role

The role will require knowledge and experience across full stack development including designing, developing, testing, publishing, and maintenance of software with strong software development principles.

As we currently are in the process of moving from a monolithic stack to a microservice based single-page application, you will need to be able to own and maintain both microservices and front-end components related to specific parts of the system.

The full stack includes technologies such as Perl, Python, React, Redux and VueJS.

## Essential Skills

- Relevant Tertiary qualifications (Degree in Computer Science / Engineering or equivalent)
- Proven working experience in software development (minimum 2 years)
- Proven experience developing RESTful API’s
- Strong front-end abilities (React/TypeScript experience preferred)
- Experience working in an Agile/Scrum development environment
- Highly motivated with a positive and collaborative attitude
- Focused with strong attention to detail
- Good written and verbal communication skills
- Willingness to innovate

If this opportunity sounds like something you would be interested in, please email michael.dorkhom@doseme.com.au for more information.

**Comment by loklaan** [comment]
👏 Great ad @MichaelDorkhom! I'll try my best to show it briefly at the next meetup.

**Comment by loklaan** [comment]
Hey @MichaelDorkhom, this is a friendly ping to check if this is still relevant?

**Comment by MichaelDorkhom** [comment]
Hi @loklaan, the position has been filled so I'll close the ad. Thanks again for the opportunity to share this here.
