### ISSUE TITLE
React and API data normalisation

### ISSUE THREAD

**Issue by patrickgordon** [reactbris/meetup#65]
## Summary of talk

Requested by #55. 
Presentation around normalising REST API data and trying to keep sane.

## Details

**Title of the Talk**  
React and API data normalisation

**Description of the Talk**  
We'll discuss what data normalisation is, and why it might be useful for your project. I'll also cover how you can do it using abstractions to reduce code duplication, as well as some of the common pitfalls, downsides, and learnings from using this in a big production app.

**My Info**  
https://www.patrick-gordon.com/
https://twitter.com/p_gord

**Comment by patrickgordon** [comment]
As mentioned can't do this months but can do 15th April

**Comment by loklaan** [comment]
@patrickgordon 👌 Looks good, can't wait! I've put it in the milestone for next month.

**Comment by iamtommcc** [comment]
@patrickgordon Hey mate, super keen for the talk - just wanted to get final confirmation that you're still good for this Monday?

**Comment by patrickgordon** [comment]
Hey yep still good.

**Comment by patrickgordon** [comment]
Hey all thanks for having me. 

Attached the slides.
[React and API data normalisation.pdf](https://github.com/reactbris/meetup/files/3082345/React.and.API.data.normalisation.pdf)
