### ISSUE TITLE
Lighting Talk: Dealing with immutable data

### ISSUE THREAD

**Issue by emanuelet** [reactbris/meetup#66]
## Summary of talk

Requested by #55.
Lighting Talk about managing immutable data with the `immutaiblity-helper` package.

## Details

**Title of the Talk**  
Dealing with immutable data

**Description of the Talk**  
I'll talk about how to leverage immutability when a React app has to talk with an API and consequently update the state in a way that considers the different state of components and maintains the performance. 

**My Info**  
@emanueletonello

**Comment by loklaan** [comment]
Thanks @emanuelet, looking forward to it! I want to pick your brain about granular observability vs immutable filtering 😊

**Comment by emanuelet** [comment]
slides for who's interested https://slides.com/emanueletonello/immutability-helper
