### ISSUE TITLE
Full-stack developer at Monarc Global

### ISSUE THREAD

**Issue by emanuelet** [reactbris/meetup#67]
![Monarc Logo](https://pbs.twimg.com/profile_images/1019802831530819585/aoU6nHlK_400x400.jpg)

Brisbane based Aviation start-up Monarc Global is looking for a full-time gun Developer. Applicant must be based in Brisbane or willing to relocate. Position available ASAP.

### Necessary skills include: 
- Node.js experience.  At least 2 years work experience.
- MYSQL and SQL experience.
- React experience.
### Desirable skills include:
- Knowledge with hosting environments and system management on servers.
- Experience with Linux and support utilities.

If this opportunity sounds like something you would be interested in, please email royce@monarcglobal.com for more information.

**Comment by loklaan** [comment]
Hey @emanuelet, friendly ping to check if this is still relevant?

**Comment by emanuelet** [comment]
it's only node js dev now actually

**Comment by loklaan** [comment]
@emanuelet No worries! Well, I'll take this one down for now as it no longer directly relates to React. But please leave a comment if the job comes back up! Have you cross-posted to brisjs? They have a similar setup for postings.
