### ISSUE TITLE
React Amsterdam wrap-up

### ISSUE THREAD

**Issue by NikChao** [reactbris/meetup#68]
## Details

**React Amsterdam Summary**  

**Description of the Talk**  
I've just returned from react-amsterdam with some lessons learnt, and stories to tell. In this talk I will go over some of the key takeaways from the conference.

**My Info**  
Twitter @nik_the_dev
Github @NikChao

**Comment by loklaan** [comment]
@NikChao Keen! I want to open with this - to cover all the lessions-learnt & stories, how long would you think it'll take? Ballpark in increments of 10minutes.

**Comment by NikChao** [comment]
@loklaan Will aim for less than 20

**Comment by loklaan** [comment]
👏 Keen

I've Loched it in for the May meetup.
