### ISSUE TITLE
React Snapshot: Get the benefits of server-side rendering, without a server!

### ISSUE THREAD

**Issue by triyuga** [reactbris/meetup#71]
## Summary of talk

Sometimes you want to make a simple "brochure" website, and you really want to get  all the SEO benefits you can from it.

React is so nice to use that it's tempting to use it all the time, but in this case, it's not a good fit.

Typically, to get SEO benefits, you need to server-side render your React application, which means setting up a server, which pretty soon starts to feel like over-kill for our simple "brochure" website...

Enter `react-snapshot`: https://github.com/geelen/react-snapshot which allows us to get the benefits of server-side rendering, really simply, and best of all, without a server!

This talk will cover:
* The problem
* The solution
* Demo
  * Snapshotting a simple app
  * Snapshotting an app that loads content asynchronously
  * A simple way to automate rebuilds for CMS-like functionality (GitHub Pages with GitHub Actions)

Estimate <= 20min talk (flexible)

Cheers,
Tim.

**Comment by triyuga** [comment]
I'm not sure if I created this with the correct label. I think it should be in `talk volunteered` rather than `talk requested` .. ?

**Comment by loklaan** [comment]
Hey @triyuga , thanks for volunteering this stuff! I had thought I'd replied last week 😬 

Are you ok to present in June?

--- 

**Early Feedback**

* We've only had one SSR talk in the past, iirc, and it was quite awhile ago. You should have an attentive audience!
* If you're up for it, it may be good to cover [more popular alternatives](https://www.npmtrends.com/react-snap-vs-react-snapshot-vs-react-static-vs-gatsby-vs-next) (afaik react-snapshot is unmaintained with react-snap superseding it within the community)
* The flow of the talk sounds legit, thanks for laying it out like that!

**Comment by triyuga** [comment]
@loklaan Yes, June will be fine. And yes I'll update the talk to incorporate your above feedback.

**Comment by loklaan** [comment]
Amazing, thanks Tim looking forward to next month.

**Comment by iamtommcc** [comment]
Hey @triyuga, looking forward to your talk on Monday 🎉

Lochie is out of town for this meetup so feel free to hit me up if you need anything before then :+1:
