### ISSUE TITLE
Rapid prototyping with React & Firebase

### ISSUE THREAD

**Issue by patrickgordon** [reactbris/meetup#72]
## Summary of talk

I've been eager to do some more side projects but rather spend time on the parts I love (front-end) and less effort on the tedious smelly things (auth, databases, and API). 

In this talk, I want to show how you can quite quickly build a "functional" web app using React and Firebase. 

## Details

**Title of the Talk**  
Rapid memes for React keen beans.
(or a title that doesn't suck?)

**Description of the Talk**  
We'll build a small web app. Like, a page

Things we'll cover:
- Overview of what Firebase is and what problems it tries to solve
- How it works together with React and why they can compliment each other
- Live coding + show a few things already added.
  - read from db and display data
  - add auth and able to login
  - show how cloud functions work and why they're neato.
- When maybe not to use Firebase?

**My Info**  
https://twitter.com/p_gord

**Comment by loklaan** [comment]
Nice one @patrickgordon 🤙 

Long-shot, but any chance this would involve attendee participation? eg. open data entry of some kind

---

Generally, very keen for talks like this! I operate on this stack at work.

**Comment by patrickgordon** [comment]
Yep we could definitely make a real time web app of some sort. I will just need internet access if possible.

**Comment by loklaan** [comment]
@patrickgordon Exciting 🙌 

Want to perform in the June meetup?

**Comment by patrickgordon** [comment]
What date is it @loklaan? I might be in Sydney for work

**Comment by loklaan** [comment]
@patrickgordon Looks like it's the 17th!

**Comment by patrickgordon** [comment]
I will check today if I'm in town @loklaan

**Comment by patrickgordon** [comment]
Yep I'm in town. Happy to do it on the 17th :)

**Comment by iamtommcc** [comment]
Can't wait @patrickgordon, see you on Monday!

**Comment by patrickgordon** [comment]
Yep seeya then @iamtommcc

**Comment by patrickgordon** [comment]
Hey all,

- Sample code: https://github.com/patrickgordon/react-firebase-example
- Slides: [React + Firebase = Rapid Prototypes.pdf](https://github.com/reactbris/meetup/files/3298914/React.%2B.Firebase.Rapid.Prototypes.pdf)
