### ISSUE TITLE
(e2e): win friends and influence people with e2e testing 

### ISSUE THREAD

**Issue by weizang-75** [reactbris/meetup#73]
## Summary of talk

A business stakeholder comes over and asks for some software to be engineered.

"*No worries,*" says I... "*That's my job after all. What exactly do you want me to do?*"  

And that's where the problems start. 

What they say and what you hear are different. 
Visa versa same. Simply put, we're talking different languages. 
Has anyone NOT seen this happen over and over?

You might very well wonder how e2e testing with Cucumber 
and Gherkin could possibly help that. Let me explain...

## Details

**Title of the Talk**  
(e2e): win friends and influence people with e2e testing 

**Description of the Talk**  
- Intro
    - What is the problem we're paying attention to?
    - What are the current solutions?
    - What does this add?
    - What are the pros and cons of adding it? 
    - etc
- Demo
    - 15 mins max; install a meaningful e2e testing on any React app
- Roadmap; Where are we going with this?
- Questions?

**My Info**  
Chris started writing JavaScript when it was disguised as ActionScript. 
He works @Rexlabs.io as a React Developer and also does other things.

- [GitHub](https://github.com/listingslab)
- [linkedin](https://www.linkedin.com/in/listingslab/)

**Comment by patrickgordon** [comment]
+1 Interested in this.

I'd also love to hear how you deal with e2e testing in a microservice arch from a CI perspective. but perhaps we can just chat about that after :)

**Comment by loklaan** [comment]
Nice Chris, this looks awesome! Honestly, there aren't testing talks out there 😆 

Would you be ok to come on to the June meetup (potentially alongside Pat 😮)

---

Early feedback is kind of in the same line as Pat above, what kind of stack scenarios are you covering? React apps come in all shapes, sizes, and data sources.

**Comment by loklaan** [comment]
BTW I started reading this book, very very good. 😄
