### ISSUE TITLE
Customising your JSX pragma for utility CSS-in-JS

### ISSUE THREAD

**Issue by jordanoverbye** [reactbris/meetup#76]
## Summary of talk

I'd like to give a talk about how you can write your own custom JSX pragma to use utility CSS frameworks (such as tailwind, tachyons or turretcss) in a CSS-in-JS syntax.

## Details

**Title of the Talk**  
Customising your JSX pragma for utility CSS-in-JS

**Description of the Talk**  

Things I'd like to cover:

- What are custom JSX pragmas
- Pros/cons/use cases on utility first CSS
- Pros/cons/use cases of CSS-in-JS
- Generating utility CSS in a CSS-in-JS syntax using a custom JSX pragma

**My Info**  
https://twitter.com/jordanoverbye?lang=en

**Comment by loklaan** [comment]
Yesss my favourite topic 👏 - would you be up for July? How long would you like to present?

---

Early feedback:
* Can't get enough CSS talks like this.
* You'll probably want to unpack the term "pragma" as quite a few attendees are just starting out (in programming)

**Comment by jordanoverbye** [comment]
Yep @loklaan I am able to do this talk in July. I'm thinking I'll talk for 20mins, maybe 25 depending how far I dive into each topic. I'll chat to you in person about this.

No worries, I'll make sure to make this talk beginner friendly. Thanks for the suggestion 🎉

**Comment by patrickgordon** [comment]
This sounds awesome!!
