### ISSUE TITLE
Using bluetooth in react native

### ISSUE THREAD

**Issue by unixbigot** [reactbris/meetup#77]
## Summary of talk

So you have a bluetooth sensor or actuator, (say a thermostat, or a door lock, or a garden sensor) and you want to control it from your app, but you'd prefer to stay in react rather than work in Java or Swift just to get access to handset hardware.   We'll look at some examples of how to do this and how to explore bluetooth low energy devices in general.

## About the speaker

Christopher Biggs is host of Brisbane Internet of Things meetup, and works as an IoT designer and consultant.

**Comment by loklaan** [comment]
@unixbigot So keen! How's your cal looking for July 15th, or August 19th? 🎉 

With such a long lead-up too, I'm thinking we could organise & pay for prizes with your talk? Like, you drop tasty facts during the talk, and at the end you have 5 questions going back to them; winners get a board. What do ya think?

**Comment by unixbigot** [comment]
Either of those dates are doable.   Your idea sounds fun, I've never done that before.   Don't let me throw prizes, I'm a klutz. :)

**Comment by iamtommcc** [comment]
@unixbigot Hey mate, looks like a really fun talk to be honest! Would you be good if we locked you in for July 15?

**Comment by unixbigot** [comment]
Yeah I can do then, @iamtommcc

**Comment by loklaan** [comment]
Looking forward to it Biggs!

I've got around finally to doing the collateral, and wanted to say thank you for a great summary & speaker blurb! 🙏
