### ISSUE TITLE
Recruitment Q&A

### ISSUE THREAD

**Issue by theharold9000** [reactbris/meetup#78]
## Summary of talk
Another installment of my long running Q&A series, designed to pull back the curtain on all things related to hiring, getting hired and my general perspective on Brisbane. Audience participation is encouraged, if not required. 

## Details

**Title of the Talk**  
Recruitment Q&A

**Description of the Talk**  
What tech is in demand? How do you ACTUALLY attract top developers? Which recruiters are actually good? All questions will be answered, you just have to ask them.

**My Info**  
@theharold9000 across all platforms.

**Comment by theharold9000** [comment]
What are the interest levels like on this @loklaan @iamtommcc?

**Comment by loklaan** [comment]
@theharold9000 OOOOPPSS I had this as unread. Yeah still keen Harold, but we'll play it by ear?

**Comment by theharold9000** [comment]
Sure, I'm perpetually at the ready so always happy to jump in with 10+ minutes

**Comment by loklaan** [comment]
Putting it in for August @theharold9000 - should be a good time for it 👀 😄

**Comment by loklaan** [comment]
@theharold9000 I've got ya in for the next one, but hit us back if other plans pop up!
