### ISSUE TITLE
Using GraphQL Subscriptions to play Sounds 🔈

### ISSUE THREAD

**Issue by xicovarisco** [reactbris/meetup#80]
## Summary of talk

How to architect a platform to play sounds in Real Time with GraphQL Subscriptions.

## Details

**Using GraphQL Subscriptions to play Sounds**  
How can we empower and excite teams using sounds on custom triggers.

**Description of the Talk**  
The idea is to explain why it's important to keep the team momentum high (specially in startups). After that I'll demonstrate how we (Askable) use a sound system to make us aware of what's going on with our clients (E.g we hooked our booking system to trigger a loud sound to us every time a client purchases something)
Lastly we do a live demo in-house :)

**My Info**  
[@xicovarisco](https://twitter.com/xicovarisco)

**Comment by loklaan** [comment]
Extremely excited for this @xicovarisco! Which night would be better for you, Aug 19th or Sept 16th?

Also when we get closer to the date please fill us in on the A/V requirements because we wanna help as much as possible.

---

_Early feedback:_ You got my thoughts during the last event! Would be stoked to have a case-study styled talk like this - there is nothing I would change.

**Comment by xicovarisco** [comment]
I believe Setp 16th would be better for me, because I have more time to prepare. Specially because I'm going to a conference in Sydney at the end of August.
Anyway.. we can lock it in. :)

**Comment by loklaan** [comment]
@xicovarisco I hope it's... campjs! 😆

Anyway yes we'll lock it in for Sept; this is good because I'll be able to make Sept too. 👍

**Comment by xicovarisco** [comment]
It's nooooot CampJS man. It's another one in Sydney (UXAustralia). We're one of the sponsors there so  I gotta got there :)
Lock it in for Sept.

**Comment by loklaan** [comment]
@xicovarisco I remember the pics of you folks at the last one! Cool!

**Comment by xicovarisco** [comment]
Yeah. That one. It will be awesome

**Comment by iamtommcc** [comment]
Hey @xicovarisco, have locked you in for Monday. Can't wait, see you on the night!

**Comment by xicovarisco** [comment]
Hey @iamtommcc. Yeah mate, can't wait to present :)
