### ISSUE TITLE
Why Redux is NOT dead

### ISSUE THREAD

**Issue by julianburr** [reactbris/meetup#81]
## Summary of talk

With context, suspense, hooks and all that other new cool stuff going on, more and more people seem to believe that Redux is finally dead. I'd try to show in this talk why this is not the case, what all these different features and patterns are actually useful for and how to pick the best solution for your problem.

## Details

**Title of the Talk**  
Redux is dead, long live Redux

**Description of the Talk**  
Why it's still relevant and alive despite the uprise of context and hooks.

**My Info**  
👋

**Comment by loklaan** [comment]
@julianburr Yaaas this is good. I recently used "redux" in a CLI and it was grand.

Would you cool to do this in Aug??

**Comment by julianburr** [comment]
Sure 😊

**Comment by loklaan** [comment]
Loched in by me, Lochlan
