### ISSUE TITLE
React hooks and the fetch API

### ISSUE THREAD

**Issue by emiaj** [reactbris/meetup#82]
## Summary of talk

React hooks provide a nice way to separate a component state and effects.   
When it comes to fetching data from an HTTP endpoint, there are a few gotchas you need to take into account in order to avoid unexpected bugs.  
In this talk, you'll learn how to use them to safely retrieve data from an external HTTP endpoint

## Details

**Title of the Talk**  
React hooks and the fetch API

**Description of the Talk**  
Effective use of React hooks and the Fetch API

**My Info**  
@jaimefebres

**Comment by loklaan** [comment]
@emiaj Hey mate! I do apologise for getting back 6 days later 😬

Thanks for volunteering the talk, it's greatly appreciated, and we'd love to have you.

Would you be available for the August 19th meetup? 😄

**Comment by emiaj** [comment]
@loklaan sure thing, count me in.
