### ISSUE TITLE
Building web applications with React, Node and GraphQL

### ISSUE THREAD

**Issue by jordanoverbye** [reactbris/meetup#84]
## Summary of talk
How to combine Keystone v5, NextJS and Apollo to build modern, performant, server-rendered web applications.

## Details

**Title of the Talk**  
Building web applications with React, Node and GraphQL

**Description of the Talk**  
How to combine Keystone v5, NextJS and Apollo to build modern, performant, server-rendered web applications.

**My Info**  
@jordanoverbye

**Comment by loklaan** [comment]
@jordanoverbye This is brilliant, can't wait! This should close #20 too 🤙

To confirm a couple things;
- [ ] This'll be for Sept 16th?
- [ ] We're hoping for 20minutes, with a cap of 30mins, all g? 😄

_My early feedback was out-of-channel_

**Comment by jordanoverbye** [comment]
Hey @loklaan

- [x] Sept 16th is fine with me 👍
- [x] Yeah I'll make sure it doesn't go over 20mins. Sorry about last time 😅

**Comment by loklaan** [comment]
> _Sorry about last time 😅_

All good, don't be sorry! It's difficult to timebox, even for seasoned speakers.

**Comment by iamtommcc** [comment]
Hey @jordanoverbye :) Have locked you in for this Monday. Any dramas, let us know.

Can't wait for it - see you on the night!
