### ISSUE TITLE
Submitting my React component as an npm package

### ISSUE THREAD

**Issue by triyuga** [reactbris/meetup#9]
I'm both requesting and volunteering this talk. I've never contributed a package to `npm` myself but want to do so. If no one else wants to take and do this talk, I would be happy to do so and use it as impetus to learn about it.

**Comment by kzima** [comment]
I have done packed few components and I remember it was a pain. Especially managing dependencies. Good topic! I wouldn't mind if you can share your experience about this.

**Comment by deecewan** [comment]
Yeah, this is an interesting one, especially setting up the toolchain to compile during release, and it becomes even more painful if you're using CSS.

**Comment by kzima** [comment]
@triyuga are you available in April to present your thoughts about submitting react package to npm?

**Comment by kzima** [comment]
@triyuga Lets push this one to May 👍

**Comment by triyuga** [comment]
Ok! Sorry @kzima only saw your comment now! Could do this one in May, or the one i just submitted: React with GraphQL and Apollo!

**Comment by loklaan** [comment]
@nk2580 HEY! 😄 

It's been touched on several times in other talks that were broader in scope. _eg. several takes/experiences on managing code for components and componentised applications_

But yeah this in isolation seems like it'd be suitable for a lightning or a short talk, depending on how deep you want to go.

Some other points that I think audience members would like to hear are:

1. Different ways of bundling & consuming css for components
2. Packaging individual components vs collection of components
    * How to manage the code of individual components
      _(Bit tooling & friends vs. homegrown monorepo + tools like yarn workspaces & lerna)_
3. Versioning UI packages
  _Should changing classNames / theming names enforce a semantic patch, minor or major change? Semantically it should be major, but does that fit the process of your team?.. probably not_
4. Where we might be in a years time with our options...

---

We have an event coming up this month on the 24th, would you like to volunteer for that night? 😉

**Comment by nk2580** [comment]
@loklaan happy to cover all those points on a talk. Unfortunately I can’t do this month. Can do next month though. The 25th?

**Comment by loklaan** [comment]
@nk2580 Brilliant, thanks! Yeah let's queue it up for next month. I'll generate a different issue for you some point today. 👍

**Comment by nk2580** [comment]
sorry for the slow reply @loklaan 
https://github.com/reactbris/meetup/issues/62 was just made
