### ISSUE TITLE
Throwing out a few ideas from the enterprise world!

### ISSUE THREAD

**Issue by TheRealFlyingCoder** [reactbris/meetup#92]
## I have no idea whether this will sound interesting!

**Background**: I've been working at Deloitte Digital for 3 years, spending the first majority of that flying between Melbs/Syd working on ridiculous digital delivery projects... there's a lot of stuff that i've done which will be foreign and hopefully interesting! Now that i'm finally back in Bris through the week I wanted to get back into the community!

Completely unprepared thoughts:

- Corporate Consulting and Code: What consulting as a dev in a high performance environment is like
- Enterprise Architecture vs Modern best practices: Attempt to bring monolithic solutions into the modern age (hint: ridiculous refactoring)
- Refactor vs Release: When to decide that your code is ready to ship based on the bigger picture, and when to take the extra time to clean it up.

I have others but also happy to just be grilled about the foreign world of consulting, i've had a lot of people interested to know how it all works :)

**Comment by iamtommcc** [comment]
Hey @TheRealFlyingCoder! Welcome to the community and apologies for not seeing your issue submission earlier!

All those topics sound like pretty interesting talk candidates to me. Enterprise Archictecture vs Modern Best Practice in praticular sounds like it'd be full of very practical takeaways.

Would you be down with doing a talk at the March meetup?
