### ISSUE TITLE
State Management In React Using Redux

### ISSUE THREAD

**Issue by Shreykhanna** [reactbris/meetup#94]
## Summary of talk
Sometimes  it become difficult to manage the components state with continuous addition  of components in react application. So we will see how to make use of powerful redux to maintain states of each component.  

## Details
**Title of the Talk**  
State Management In React Using Redux

**Description of the Talk**  
The talk will be about what is redux, how to integrate it to react and its implementation. 

**My Info**  
@khannashrey07

**Comment by iamtommcc** [comment]
Hey @Shreykhanna, hope you're well mate :) And thanks for volunteering a talk.

Redux talks are always a great topic, but most of ReactBris' audience nowadays has a lot of exposure to Redux so there may not be a huge appetite for a talk on Redux basics.

You could look at pivoting the talk topic into more advanced Redux usage if you feel up to it.

Let me know what you think.

**Comment by Shreykhanna** [comment]
Hi @iamtommcc . I need some time to think on advance usage of redux, so will not be able to present in this meetup. Maybe will come up with something for next meetups. :-)
